# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
import sys
import os
from pathlib import Path
from docutils.nodes import literal_block
from pygments.lexers import ClassNotFound, find_lexer_class_by_name
from sphinx.locale import __
from sphinx.transforms.post_transforms import SphinxPostTransform
ROOT = Path(__file__).resolve().parents[1]
sys.path.extend([str(ROOT/'src'), str(ROOT/"doc")])
from utils.icon import icon_links
# Define the canonical URL if you are using a custom domain on Read the Docs
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "https://xinetzone.github.io/tvm-book")

# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    if "html_context" not in globals():
        html_context = {}
    html_context["READTHEDOCS"] = True
# 国际化
# https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/i18n.html
# from sphinx.locale import get_translation
# catalog = "theme"
# _ = get_translation(catalog)
if sys.platform == 'win32':
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

project = 'tvm-book'
copyright = '2022, xinetzone'
author = 'xinetzone'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_nb',
    'sphinx.ext.intersphinx',
    'sphinx_copybutton',
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
    'sphinx.ext.autosectionlabel',
    "sphinx.ext.graphviz",
    "matplotlib.sphinxext.plot_directive",
    "sphinx_automodapi.automodapi",
    "sphinx_automodapi.smart_resolver",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx_thebe",
    "sphinx_sitemap",
    "sphinx_design",
    "sphinx_comments",
    "sphinxcontrib.mermaid",
    "sphinx_plotly_directive",
    # "sphinx.ext.todo",
    "autodocsumm",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx_automodapi.automodapi",
    "sphinx_automodapi.smart_resolver",
    'autoapi.extension',
    "sphinxcontrib.icon",
]

autodoc_default_options = {
    'autosummary': True,
}

suppress_warnings = [
    "mystnb.unknown_mime_type",  # 禁用 application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json 警告
    "myst.xref_missing", # 禁用 myst 警告
    "autoapi.python_import_resolution", "autoapi.not_readable" # 禁用 autoapi 警告
    "sphinx_automodapi.automodapi",
    "autosectionlabel.*", "autosummary", "intersphinx.external",
    "autodoc", "autodoc.import_object"
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'xyzstyle'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = [
    'custom.css',
]

# MyST-NB 设置
# 如果你希望stderr和stdout中的每个输出都被合并成一个流，请使用以下配置。
# 避免将 jupter 执行报错的信息输出到 cmd
nb_merge_streams = True
nb_execution_allow_errors = True
nb_execution_mode = 'off'
nb_execution_excludepatterns = []
nb_mime_priority_overrides = [
    ("html", "text/html", 0),
    ("latex", "text/latex", 20),
    ("html", "application/vnd.plotly.v1+json", 10),
    # ("image", "image/svg+xml", None)
    # (
    #     "application/vnd.jupyter.widget-view+json",
    #     "application/javascript",
    #     "text/html",
    #     "image/svg+xml",
    #     "image/png",
    #     "image/jpeg",
    #     "text/markdown",
    #     "text/latex",
    #     "text/plain",
    # ), 0)
]

# -- 国际化输出 ----------------------------------------------------------------
gettext_compact = False
locale_dirs = ['locales/']

autosummary_generate = True
# Napoleon 设置
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

html_logo = '_static/images/logo.jpg'
# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/images/favicon.jpg'
html_last_updated_fmt = '%Y-%m-%d, %H:%M:%S'

extlinks = {
    # 'duref': ('https://docutils.sourceforge.io/docs/ref/rst/'
    #           'restructuredtext.html#%s', ''),
    # 'durole': ('https://docutils.sourceforge.io/docs/ref/rst/'
    #            'roles.html#%s', ''),
    # 'dudir': ('https://docutils.sourceforge.io/docs/ref/rst/'
    #           'directives.html#%s', ''),
    'py-doc': ('https://daobook.github.io/cpython/%s', ''),
    'daobook': ('https://daobook.github.io/%s', ''),
}

intersphinx_mapping = {
    'python': ('https://daobook.github.io/cpython/', None),
    'tvm': ('https://xinetzone.github.io/tvm/', None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
}

# ``pydata-sphinx-theme`` 配置
# Define the json_url for our version switcher.
json_url = 'https://xinetzone.github.io/tvm-book/_static/switcher.json'
# ReadTheDocs has its own way of generating sitemaps, etc.
if not os.environ.get("READTHEDOCS"):
    extensions += ["sphinx_sitemap"]
    html_baseurl = os.environ.get("SITEMAP_URL_BASE", "http://127.0.0.1:8000/")
    sitemap_locales = [None]
    sitemap_url_scheme = "{link}"
# Define the version we use for matching in the version switcher.
version_match = os.environ.get("READTHEDOCS_VERSION")

html_theme_options = {
    "path_to_docs": "doc",
    "github_url": "https://github.com/xinetzone/tvm-book",
    "repository_url": "https://github.com/xinetzone/tvm-book",
    "repository_branch": "main",
    "launch_buttons": {
        "binderhub_url": "https://mybinder.org",
        "colab_url": "https://colab.research.google.com/",
        "deepnote_url": "https://deepnote.com/",
        "notebook_interface": "jupyterlab",
        "thebe": True,
        # "jupyterhub_url": "https://datahub.berkeley.edu",  # For testing
    },
    "use_edit_page_button": True,
    "use_source_button": True,
    "use_issues_button": True,
    # "use_repository_button": True,
    "use_download_button": True,
    "use_sidenotes": True,
    "show_toc_level": 5,
    "announcement": (
        "👋欢迎进入 AI 世界！👋"
    ),
    "navigation_with_keys": True,
    "icon_links": icon_links,
    "switcher": {
        "json_url": json_url,
        "version_match": version_match,
    },
    "collapse_navigation": True,
    # "navbar_start": ["test.html"],
    # "navbar_center": ["test.html"],
    # "navbar_end": ["test.html"],
    # "navbar_persistent": ["test.html"],
    # "secondary_sidebar_items": {
    #     "**/*": ["page-toc", "edit-this-page", "sourcelink", ],
    #     "examples/no-sidebar": [],
    # },
    # "primary_sidebar_end": ["sidebar-ethical-ads", ],
    # "article_footer_items": ["test", "test"],
    # "content_footer_items": ["test", "test"],
    "footer_start": ["version-switcher", "copyright"],
    "footer_end": ["sphinx-version", "last-updated"],
}

# html_sidebars = {
#     "*": ["sidebar-nav-bs.html", "sidebar-ethical-ads.html"]
#     # "**": [],
# }

html_context = {
    "github_user": "xinetzone",
    "github_repo": "tvm-book",
    "github_version": "main",
    "doc_path": "doc",
}

myst_enable_extensions = [
    "colon_fence",
    "amsmath",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

bibtex_bibfiles = ["d2ltvm.bib"]
# To test that style looks good with common bibtex config
bibtex_reference_style = "author_year"
graphviz_output_format = 'svg'

comments_config = {
    "hypothesis": True,
    "dokieli": False,
    "utterances": {
        "repo": "xinetzone/tvm-book",
        "optional": "config",
    }
}

todo_include_todos = True

# -- Options for autosummary/autodoc output ------------------------------------
autosummary_generate = True
autodoc_typehints = "description"
autodoc_member_order = "groupwise"

# -- Options for autoapi -------------------------------------------------------
autoapi_type = "python"
autoapi_dirs = ["../src/tvm_book"]
autoapi_keep_files = False # 要开始自己编写 API 文档，你可以让 AutoAPI 保留其生成的文件作为基础
autoapi_root = "api"
autoapi_member_order = "groupwise"

class LexerValidation(SphinxPostTransform):
    """参考：https://github.com/sphinx-doc/sphinx/issues/11442"""
    default_priority = 500
    builders = ('dummy',)

    def __init__(self, *args, **kwargs):
        from sphinx.highlighting import lexers, lexer_classes, logger

        super().__init__(*args, **kwargs)
        self.lexer_names = lexers.keys() | lexer_classes.keys()
        self.logger = logger

    def run(self, **kwargs):
        for node in self.document.findall(literal_block):
            lang = node.get('language', 'default')
            self.logger.info(f"lang, node: {lang, node}")
            self.validate_lexer(lang, node)

    def validate_lexer(self, lang, location):
        if lang in {'py', 'py3', 'python3', 'default', 'pycon3'}:
            lang = 'python'

        if lang in {'C++14', 'C++17', 'C++', 'C++20', 'C++11'}:
            lang = 'cpp'

        if lang in self.lexer_names:
            return

        try:
            lexer = find_lexer_class_by_name(lang)
        except ClassNotFound:
            self.logger.warning(__('Pygments lexer name %r is not known'), lang,
                                location=location)

def setup(app):
    app.add_post_transform(LexerValidation)
